import type { Transaction } from "@/lib/types";
import {
  Banknote,
  Car,
  ChevronDown,
  CreditCard,
  Gift,
  Home,
  PiggyBank,
  Plus,
  ReceiptText,
  TrendingUp,
  Wallet,
} from "lucide-react";

export const transactions: Transaction[] = [
  {
    id: "1",
    date: "2024-07-15",
    amount: 75.5,
    category: "Groceries",
    type: "expense",
    description: "Weekly grocery shopping at Walmart",
    icon: Wallet,
  },
  {
    id: "2",
    date: "2024-07-15",
    amount: 3000,
    category: "Salary",
    type: "income",
    description: "Monthly salary",
    icon: Banknote,
  },
  {
    id: "3",
    date: "2024-07-14",
    amount: 45.0,
    category: "Transport",
    type: "expense",
    description: "Uber ride to the airport",
    icon: Car,
  },
  {
    id: "4",
    date: "2024-07-13",
    amount: 1200,
    category: "Rent",
    type: "expense",
    description: "Monthly rent payment",
    icon: Home,
  },
  {
    id: "5",
    date: "2024-07-12",
    amount: 15.0,
    category: "Subscriptions",
    type: "expense",
    description: "Netflix monthly subscription",
    icon: ReceiptText,
  },
  {
    id: "6",
    date: "2024-07-11",
    amount: 500,
    category: "Investment",
    type: "expense",
    description: "Stocks investment",
    icon: TrendingUp,
  },
  {
    id: "7",
    date: "2024-07-10",
    amount: 250,
    category: "Freelance",
    type: "income",
    description: "Payment for freelance work",
    icon: PiggyBank,
  },
];
