version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finsight-web
    ports:
      - "3091:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - GEMINI_API_KEY=AIzaSyBx8OZS3ISiG1mlHZqSQkY1bo74gkG1UIM
    restart: unless-stopped
